version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=senha_secreta
      - DB_NAME=minha_api
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_secreta
      POSTGRES_DB: minha_api
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
